version: '3'
services:
  nss_almalinux9:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.almalinux-9
    volumes:
      - .:/stns
    environment:
      DIST: el9
    command: make rpm
  nss_centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
    volumes:
      - .:/stns
    environment:
      DIST: el7
    command: make rpm
  nss_ubuntu20:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-20
    volumes:
      - .:/stns
    environment:
      DIST: focal
    command: make deb
  nss_ubuntu22:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-22
    volumes:
      - .:/stns
    environment:
      DIST: jammy
    command: make deb
  nss_ubuntu24:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-24
    volumes:
      - .:/stns
    environment:
      DIST: noble
    command: make deb
  nss_debian10:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-10
    volumes:
      - .:/stns
    environment:
      DIST: buster
    command: make deb
  nss_debian11:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-11
    volumes:
      - .:/stns
    environment:
      DIST: bullseye
    command: make deb
  nss_debian12:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-12
    volumes:
      - .:/stns
    environment:
      DIST: bookworm
    command: make deb
