version: '3'
services:
  nss_centos8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-8
    volumes:
      - .:/stns
    environment:
      DIST: el8
    command: make rpm
  nss_centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
    volumes:
      - .:/stns
    environment:
      DIST: el7
    command: make rpm
  nss_ubuntu18:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-18
    volumes:
      - .:/stns
    environment:
      DIST: bionic
    command: make deb
  nss_ubuntu20:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-20
    volumes:
      - .:/stns
    environment:
      DIST: focal
    command: make deb
  nss_ubuntu22:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-22
    volumes:
      - .:/stns
    environment:
      DIST: jammy
    command: make deb
  nss_debian10:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-10
    volumes:
      - .:/stns
    environment:
      DIST: buster
    command: make deb
  nss_debian11:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-11
    volumes:
      - .:/stns
    environment:
      DIST: bullseye
    command: make deb
