FROM almalinux:9

RUN dnf install -y \
    glibc \
    gcc \
    make \
    unzip \
    rpmdevtools \
    perl \
    clang \
    git

RUN mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
RUN sed -i "s;%_build_name_fmt.*;%_build_name_fmt\t%%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.el9.rpm;" /usr/lib/rpm/macros

RUN mkdir /stns
WORKDIR /stns
