FROM ubuntu:focal
MAINTAINER pyama86 <www.kazu.com@gmail.com>

ENV EBIAN_FRONTEND noninteractive
RUN apt-get -qqy update && \
    apt-get install -qqy \
    tzdata \
    glibc-source \
    gcc \
    make \
    bzip2 \
    unzip \
    debhelper \
    dh-make \
    devscripts \
    cdbs \
    clang \
    git

ENV LIBDIR /usr/lib
ENV USER root
RUN mkdir /stns
WORKDIR /stns
