FROM centos:8
MAINTAINER pyama86 <www.kazu.com@gmail.com>

RUN yum install -y glibc gcc make bzip2 unzip rpmdevtools epel-release && \
    yum install -y clang

RUN mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
RUN sed -i "s;%_build_name_fmt.*;%_build_name_fmt\t%%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.el8.rpm;" /usr/lib/rpm/macros

RUN mkdir /stns
WORKDIR /stns
