FROM debian:stretch
MAINTAINER pyama86 <www.kazu.com@gmail.com>

RUN apt-get -qqy update && \
    apt-get install -qqy glibc-source gcc make \
                        bzip2 unzip debhelper dh-make devscripts cdbs clang libssl-dev openssl zlib1g-dev

ENV USER root
RUN mkdir /stns
WORKDIR /stns
