on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
env:
    COMPOSE_FILE: docker-compose.yaml
name: Release
jobs:
  build:
    timeout-minutes: 120
    strategy:
      matrix:
        include:
          - arch: arm64
            runner: ubuntu-24.04-arm
          - arch: amd64
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: build
        run: make pkg
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
      - name: donwload ghr
        run: |
          curl -L -O -s https://github.com/tcnksm/ghr/releases/download/v0.16.2/ghr_v0.16.2_linux_${{ matrix.arch }}.tar.gz
          tar zxf ghr_v0.16.2_linux_${{ matrix.arch }}.tar.gz
          sudo mv ghr_v0.16.2_linux_${{ matrix.arch }}/ghr /usr/bin
      - name: release
        run: make github_release
